// Automatically generated by astro-icon
// 48ecd64cfa267a7bdb881f844130460abe495e74778e13d8042c186a6d815156

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-right"
		| "css-3"
		| "github"
		| "html-5"
		| "instagram"
		| "javascript"
		| "linkedin"
		| "mail"
		| "mitarjeta"
		| "next"
		| "python"
		| "react"
		| "tailwindcss"
		| "twitter"
		| "whatsapp"
		| "whatsapp2";
}